#include "config_winui/wanxiang_modes.h"

#include "common/constants.h"

namespace fp::config_winui {

const std::array<WanxiangModeDefinition, 14>& WanxiangModeDefinitions() {
  static constexpr std::array<WanxiangModeDefinition, 14> modes{{
      {L"反查拆字",
       L"使用 ` 引导部件拼音、笔画和辅助码反查。",
       fp::kWanxiangReverseLookupEnabledSetting,
       true,
       L"`",
       fp::kLegacyUModeSetting},
      {L"Unicode 码位",
       L"使用 U 加十六进制码位输入字符。",
       fp::kWanxiangUnicodeEnabledSetting,
       true,
       L"U",
       fp::kLegacyUModeSetting},
      {L"数字金额",
       L"使用 R 引导中文数字和财务大写。",
       fp::kWanxiangNumberEnabledSetting,
       true,
       L"R",
       fp::kLegacyVModeSetting},
      {L"日期时间",
       L"使用 N 或斜杠命令输入日期时间。",
       fp::kWanxiangDateEnabledSetting,
       true,
       L"N",
       fp::kLegacyVModeSetting},
      {L"超级计算器",
       L"使用 V 输入表达式、换算和计算。",
       fp::kWanxiangCalculatorEnabledSetting,
       true,
       L"V",
       fp::kLegacyVModeSetting},
      {L"符号表",
       L"使用 / 加数字或字母输出符号表。",
       fp::kWanxiangSymbolEnabledSetting,
       true,
       L"/",
       L""},
      {L"快捷符号",
       L"使用单字母命令快速上屏符号。",
       fp::kWanxiangQuickSymbolEnabledSetting,
       false,
       L"a/",
       L""},
      {L"成对符号包裹",
       L"使用命令包裹候选文字和标记。",
       fp::kWanxiangPairedSymbolEnabledSetting,
       true,
       L"\\",
       L""},
      {L"英文词库",
       L"启用英文候选、大小写格式化和中英混排辅助。",
       fp::kWanxiangEnglishEnabledSetting,
       true,
       L"En",
       L""},
      {L"混合编码",
       L"启用中英数字混合候选。",
       fp::kWanxiangMixedCodeEnabledSetting,
       true,
       L"Mix",
       L""},
      {L"输入统计",
       L"启用输入统计查询和记录。",
       fp::kWanxiangInputStatisticsEnabledSetting,
       false,
       L"统",
       L""},
      {L"自动造词",
       L"启用自动造词和英文造词过滤器。",
       fp::kWanxiangAutoPhraseEnabledSetting,
       true,
       L"词",
       L""},
      {L"手动造词",
       L"启用手动创建用户词入口。",
       fp::kWanxiangUserPhraseEnabledSetting,
       false,
       L"``",
       L""},
      {L"方案命令",
       L"启用输入方案切换命令。",
       fp::kWanxiangSchemaShortcutsEnabledSetting,
       false,
       L"命",
       L""},
  }};
  return modes;
}

}  // namespace fp::config_winui
